# Generated by Django 3.2.3 on 2021-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=40)),
                ('age', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('wallet', models.FloatField()),
                ('order_count', models.IntegerField()),
            ],
        ),
    ]
