# Generated by Django 3.2.3 on 2021-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210526_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_process', 'in_process'), ('closed', 'closed')], default='in_process', max_length=15),
        ),
    ]
